### PR TITLE
Fix colors in JS and PHP

### PR DESCRIPTION
**Pull request by wackyMole**
Recover "orange" color for variables in PHP
Recover "blue" color for types in PHP
Recover white color for variable.function in JS (without messing
up PHP's types)

### CODE REVIEW

**Comment by wackyMole** [comment]
Unfortunately, I don't know what JS variable.function's were supposed to be previously, so I set it to white for now. That helps break up the JS wall of orange, but is likely less than preferred. However, it does make it consistent with PHP's method calls on variables.

If someone can let me know what it should be, I'll update the PR to include the correct color.

**Comment by wackyMole** [comment]
Heh, accidentally clicked the wrong button.

**Comment by kenwheeler** [comment]
lollerblades.Can you hit me with a before/after screenshot?

**Comment by wackyMole** [comment]
Certainly!

PHP Before (Notice the "orange" type declarations and the "white" variables):
screenshot from 2016-03-23 22 50 07

PHP After ("blue" type declarations and "orange" variables):
screenshot from 2016-03-23 22 58 52

JS Before (Notice the excessive white variables and function calls, which both turn "orange" when reverting to the "orange" PHP variables above):
screenshot from 2016-03-23 22 53 17

JS After ("orange" variable names, white function calls):
screenshot from 2016-03-23 22 57 13

**Comment by kenwheeler** [comment]
Swag

**Pull request merged**
