### PR TITLE
Improved selection coloring

### PR DESCRIPTION
**Pull request by myfancypants**
Utilized existing color scheme values and improved selection highlighting color. Dramatically increases readability

### CODE REVIEW

**Comment by ericskao** [comment]
I would love to see this feature implemented! Makes highlighted text much easier to read.

**Comment by IanConery** [comment]
This is an amazing improvement, this should be merged immediately.

**Comment by sara-gudeman** [comment]
This is awesome. Serious improvement.

**Comment by richardstanley** [comment]
This is cool.

**Pull request merged**
